# Generated by Django 5.1.3 on 2024-12-03 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_alter_shift_end_time_alter_shift_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shifts.branch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved')], default='draft', max_length=10),
        ),
    ]
