# Generated by Django 5.1.3 on 2025-03-12 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0004_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField()),
                ('day', models.CharField(max_length=10)),
                ('shift_type', models.CharField(max_length=20)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifts.branch')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_preferences', to='shifts.employee')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifts.room')),
            ],
            options={
                'unique_together': {('employee', 'week_start_date', 'day', 'shift_type', 'room')},
            },
        ),
    ]
